# for local clusters, applies grafana user keys and tokens
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: default
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-main
        namespace: default
        port: web
  image: quay.io/prometheus/prometheus:v2.22.1
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.22.1
  remoteWrite:
    - url: 'https://prometheus-us-central1.grafana.net/api/prom/push'
      basicAuth:
        username:
          name: kubepromsecret
          key: '750773'
        password:
          name: kubepromsecret
          key: 'eyJrIjoiOWVlMDRiMWI5NTNlYWM4ODY5MTQ5Zjk4MTE2YjRiNWJiYmEwMDQ0OSIsIm4iOiJQb3NlZGlvbiIsImlkIjo3ODQ5NjJ9'
  replicaExternalLabelName: '__replica__'
  externalLabels: { cluster: 'test' }
